services:
  app:
    build: ./
    container_name: jwt_auth
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "./migrations", "-database", "postgres://postgres:123@db:5432/rest_auth?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
